### ISSUE TITLE
[BUG] no data coming through live measurement

### ISSUE THREAD

**Issue by TobTkyDev** [BeatsuDev/tibber.py#30]
## Describe the bug
Although, I have played with my personal token and different variations, I never get anything out of LiveMeasurement. All static data like name, address, home id, etc. I can get without any issue. So, to keep it simple I went back to your latest example including  the user_agent. When I run the example the Python shell get stuck and doesn't show anything, no error, nothing; only reset will recover.

## To Reproduce
I'm running python 3.11.0 on a Mac and I have a Tibber Pulse installed at my house (although demo token shows same beauvoir). 

# code snippet

import tibber

account = tibber.Account(tibber.DEMO_TOKEN)
home = account.homes[0]

@home.event("live_measurement")
def show_current_power(data):
  print(data.power)

home.start_live_feed(user_agent = "UserAgent/0.0.1") 

## Full error / traceback here
Python Shell doesn't show anything.

## Expected behavior
getting power data or last meter consumption via live measurement 

## Screenshots
na

## Version
0.3.0

## Additional context
na

**Comment by BeatsuDev** [comment]
That's very weird... It seems to work for me (using the demo token). 
![image](https://user-images.githubusercontent.com/35773677/212752872-dd0b79dd-ca21-4562-b5a3-86bb8eafa4c7.png)

Here's the code in text format:
```py
import tibber

account = tibber.Account(tibber.DEMO_TOKEN)
home = account.homes[0]

@home.event("live_measurement")
def show_current_power(data):
    print(data.power)

home.start_live_feed(user_agent = "UserAgent/0.0.1")
```

Could you try adding logging before your code and see if there is any output from that?
```py
import logging

logger = logging.getLogger("tibber")
logger.basicConfig()
logger.setLevel(logging.DEBUG)

import tibber

...
```

**Comment by BeatsuDev** [comment]
Also, could you double check that you are running the correct version of tibber?

```py
import tibber
print(tibber.__version__)
```

**Comment by BeatsuDev** [comment]
I just fixed a typo in the logging snippet, so you might have to copy paste it again.

**Comment by TobTkyDev** [comment]
Hey, thanks for your quick response. When I run the code with your debugger I've got the cache it seems and the Shell became super slow, too many data to display, I assume.

Just the beginning of the data:


============== RESTART: /Users/Tobias/Documents/Stromverbrauch.py ==============
0.3.0
DEBUG:tibber.account:Overwriting the cache data.
DEBUG:tibber.account:Old data: {}
DEBUG:tibber.account:New data: {"viewer": {"login": "arya@winterfell.com", "userId": "dcc2355e-6f55-45c2-beb9-274241fe450c", "name": "Arya Stark", "accountType": ["tibber", "customer"], "homes": [{"id": "96a14971-525a-4420-aae9-e5aedaa129ff", "timeZone": "Europe/Stockholm", "appNickname": "Vitahuset", "appAvatar": "FLOORHOUSE3", "size": 195, "type": "HOUSE", "numberOfResidents": 5, "primaryHeatingSource": "GROUND", "hasVentilationSystem": false, "mainFuseSize": 25, "address": {"address1": "Winterfell Castle 1", "address2": null, "address3": null, "city": null, "postalCode": null, "country": null, "latitude": null, "longitude": null}, "owner": {"id": "dcc2355e-6f55-45c2-beb9-2742 ...

**Comment by TobTkyDev** [comment]
When I run the py script from the Terminal I get the same behavior (no output). However, when I kill the program with ^C I get lots of information. What I can see is, there is an ssl certificate issue and some Type Error. See below:

TL-MBPn:Documents Tobias$ python3.11 Stromverbrauch.py
^CTask exception was never retrieved
future: <Task finished name='Task-16' coro=<ReconnectingAsyncClientSession._connection_loop() done, defined at /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gql/client.py:1330> exception=TypeError('catching classes that do not inherit from BaseException is not allowed')>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gql/transport/websockets_base.py", line 490, in connect
    self.websocket = await asyncio.wait_for(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 684, in _wrap_awaitable
    return (yield from awaitable.__await__())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 479, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/websockets/legacy/client.py", line 663, in __await_impl__
    _transport, _protocol = await self._create_connection()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1098, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1131, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py", line 577, in _on_handshake_complete
    raise handshake_exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py", line 559, in _do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/gql/client.py", line 1342, in _connection_loop
    await self._connect_with_retries()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/backoff/_async.py", line 152, in retry
    except exception as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
TL-MBPn:Documents Tobias$

**Comment by TobTkyDev** [comment]
That might help: https://stackoverflow.com/questions/70236730/ssl-sslcertverificationerror-ssl-certificate-verify-failed-certificate-verif

**Comment by TobTkyDev** [comment]
After some research I found a solution to fix the certification issue. From what I can tell this is an issue with rather MacOS than Windows.

1. Install the module certifi by entering the following in the terminal: pip3.11 install certifi
2. Run the following command in terminal: /Applications/Python\ 3.11/Install\ Certificates.command

After these two steps the live measurement is running on my Mac.

**Comment by BeatsuDev** [comment]
> After some research I found a solution to fix the certification issue. From what I can tell this is an issue with rather MacOS than Windows.
> 
> 1. Install the module certifi by entering the following in the terminal: pip3.11 install certifi
> 2. Run the following command in terminal: /Applications/Python\ 3.11/Install\ Certificates.command
> 
> After these two steps the live measurement is running on my Mac. 
> 

Interesting, that's good to know... Thanks!
